name: tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install testing and linting dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov
            pip install -r requirements.txt

      # - name: Run linting tests
      #   run: flake8 sloth --count --statistics --show-source

      - name: Run unit tests
        run: |
          cd tests
          pytest --cov=sloth --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: tests/htmlcov
